### ISSUE TITLE
大佬好，想求一份sql

### ISSUE THREAD

**Issue by mrgu1609** [shansec/go-vue-admin#23]
大佬好，

**Comment by shansec** [comment]
gorm 会自动创建表，不需要 sql。

**Comment by mrgu1609** [comment]
里面的数据不会搞



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年06月22日 09:24 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [shansec/go-vue-admin] 大佬好，想求一份sql (Issue #23) |

gorm 会自动创建表，不需要 sql。

**Comment by mrgu1609** [comment]
看到了，看到了，感谢大佬
